stages:
  split_data:
    cmd: python src/data_split.py
    deps:
      - src/data_split.py
      - data/raw/raw.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  normalize_data:
    cmd: python src/data_normalize.py
    deps:
      - src/data_normalize.py
      - data/processed/X_train.csv
      - data/processed/X_test.csv
    outs:
      - data/processed/X_train_scaled.csv
      - data/processed/X_test_scaled.csv

  grid_search:
    cmd: python src/grid_search.py
    deps:
      - src/grid_search.py
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
    outs:
      - models/best_params.pkl
      - metrics/grid_search_report.txt

  train_model:
    cmd: python src/train_model.py
    deps:
      - src/train_model.py
      - models/best_params.pkl
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
    outs:
      - models/random_forest_model.pkl
      - metrics/scores.json
